print("What is your name?")
name = str(input())
print("\nHow old are you (in years)?")
age = int(input())
print("\nHow tall are you (in meters)?")
height = float(input())
print("\nHow much do you weigh (in kg)?")
weight = float(input())
bmi = weight / (height**2)
#print(bmi)
print(name," you are ",age," years old and your bmi is ",bmi,".")